### ISSUE TITLE
Job submission error message when files are not writable

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#102]
> The job submit could use better error messaging. For example, I was getting an error because the directory I was specifying didn't exist and the info button was not helpful in determining what was wrong.

We should provide the error message to the user.

![image](https://cloud.githubusercontent.com/assets/79268/22155466/1f2d900c-def5-11e6-8511-be707af97f7f.png)

**Comment by adamfitzgibbon** [comment]
While looking into this issue I found a couple things that I was curious about. First, the ng-pattern for location was commented out, did we decide to not constrain users to slurm files ending in .slurm or was this a mistake? Also I found that the symbols at the right of the file location text boxes were only red x's when it was a fileWritable error, not anything else. I thought it was slightly weird to have a green check mark along with an error saying that the file extension was wrong, but was this also intended?

**Comment by djw8605** [comment]
`ng-pattern` wasn't suppose to be commented out.  git blame blames me in fb203b2700715840062b7b8d84cdb7e7840a26df, so my bad.  Put it back in.

Yeah, feel free to tie the checkmarks to the pattern.  I guess I didn't do that, but you should be able to do that with the ng-class statements.  Maybe something like writable && fits_pattern?

**Comment by adamfitzgibbon** [comment]
Addressed in #175
