### ISSUE TITLE
Error when exiting out of Duo authentication screen.

### ISSUE THREAD

**Issue by caseylargent** [unlhcc/HCCGo#120]
When the 2 factor is not completed (exit out spontaneously), the app is stuck on waiting for that authentication.

**Comment by cjkeilig** [comment]
I am not having this problem, but I think the duo auth behavior may have changed a little bit. Even if I close the app when duo is waiting for a response and then approve the authentication on my phone, duo works as expected when HCCGo is relaunched.
The other thing is that clicking outside of the duo modal prompt will hang the application, the 'backdrop' here disables clicking outside the duo prompt.
`$("#promptModal").modal({show: 'true',backdrop:'static'});`
