### ISSUE TITLE
Git Clone to Cluster Button

### ISSUE THREAD

**Issue by caseylargent** [unlhcc/HCCGo#121]
Takes a URL and clones the git repository to the current cluster. Possibly a part of an options page?

Adding TODO List:
- [x] Read in job submit files from the repo's `package.json` file.
- [x] Fade out the tutorial while loading it's repo data.
- [x] Fix progress bar on tutorials page, not updating correctly.
- [x] Add text, probably in markdown like beta_notice.md, to the side bar of the Tutorials page.
- [x] HTML escape everything we read in from the repo's `package.json`, for safety.
- [x] Interpret `$WORK` from package.json and convert it to their work directory. 32c509dc3b640f24239296e7dc34360cc765abf7
- [x] Add support for tags from the package.json c433a8b1a3ef39668c3359c1997ff724100534bc
- [x] Update the package.json to include modules
- [x] User message stating where the files for the tutorial were loaded

**Comment by CarrieBrown** [comment]
Please use this repo: https://github.com/unlhcc/HCCGoWorkshops

**Comment by djw8605** [comment]
@caseylargent What about this idea:

- Make a new view, call it Tutorials.
- In the middle of the screen, have a ng-repeat (copy from the cluster landing page) to show the different git repos to clone.
- Pull the data from a tutorials.json in the `data` directory.  The tutorials.json will be an array of tutorials, with metadata like Description, Git repo, Name, list of topics...
- (Bonus points) When the user clicks a tutorial, have it redirect them to the job submission page, with an example submission already filled out.

**Comment by CarrieBrown** [comment]
If you do point 4, [the original repo](https://github.com/unlhcc/HCCWorkshops) has existing submit files that you could parse into the submission form.

**Comment by djw8605** [comment]
I have the beginning of a tutorials page on my repo, branch `add_tutorials`.  @caseylargent please start there.

![image](https://cloud.githubusercontent.com/assets/79268/23084835/fb5eaa08-f529-11e6-8b89-4715e29ce258.png)

**Comment by djw8605** [comment]
@caseylargent I've done a bunch of this work this weekend.  When you work on this, start from my add_tutorials branch.

What needs to still be done:

- [ ] Read in job submit files from the repo's `package.json` file.
- [ ] Fade out the tutorial while loading it's repo data.
- [ ] Fix progress bar on tutorials page, not updating correctly.
- [ ] Add text, probably in markdown like beta_notice.md, to the side bar of the Tutorials page.
- [ ] HTML escape everything we read in from the repo's `package.json`, for safety.

Here is the diff, so far:
https://github.com/djw8605/HCCGo/compare/master...djw8605:add_tutorials

And a screenshot of the tutorials page:
![image](https://cloud.githubusercontent.com/assets/79268/23125974/2dfaeabe-f73a-11e6-98e7-2056b7513cae.png)

**Comment by CarrieBrown** [comment]
Some items of note:
 - loading a tutorial more than once duplicates the submit file
 - is it possible to have the load module lines appear in the modules field as opposed to commands?
 - some way to display tutorial text would be helpful (such as the README.md file or just a link to the github pages for the repo)
 - user message stating where the files for the tutorial were loaded

**Comment by djw8605** [comment]
I've added a few of these items to the checklist above.

For the tutorial text, the "Description" is configured in the package.json.  Also, below the description, the Github link goes to the Repo, where the README.md is on the front page.

**Comment by djw8605** [comment]
@caseylargent I fixed a few things.  Be sure to pull before you start working on it again.

Also, the tutorial should be faded while it's getting the package.json, not while it's installing the tutorial.

**Comment by djw8605** [comment]
@CarrieBrown Here is the tutorial page with your text:
![image](https://cloud.githubusercontent.com/assets/79268/23224026/60528cce-f8f2-11e6-95b0-87c9ba684c18.png)

**Comment by CarrieBrown** [comment]
That looks great!
