### ISSUE TITLE
Autofill the work directory for location, error, and output.

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#13]
Autofill the work directory for location, error, and output in the job submission form.  You should be able to discover it.

**Comment by adamfitzgibbon** [comment]
Should I set the default to be just the base user directory, i.e. /work/swanson/afitz/job.slurm ?

**Comment by djw8605** [comment]
How about, set the default to the base work directory, but leave everything after empty.  On the next version, we will implement the hccgo sandbox, where all hccgo related things will go.

**Comment by adamfitzgibbon** [comment]
Alright, that should work.
