### ISSUE TITLE
Failing to specify full path on err and out files shows no error but job fails

### ISSUE THREAD

**Issue by CarrieBrown** [unlhcc/HCCGo#142]
Putting just file names (as opposed to full paths) shows the green checkmark, but the job fails.

Note: I am making the assumption that it is failing because of this reason, it could be something else. I copied the submit file to a text document on the cluster and was able to run the job correctly.

![screen shot 2017-02-02 at 2 43 30 pm](https://cloud.githubusercontent.com/assets/13242287/22567682/8f912596-e956-11e6-9345-96480eaa21a9.png)

![screen shot 2017-02-02 at 2 45 21 pm](https://cloud.githubusercontent.com/assets/13242287/22567688/95c96b6c-e956-11e6-9002-1b0741d0ddf1.png)

<img width="944" alt="screen shot 2017-02-02 at 2 50 25 pm" src="https://cloud.githubusercontent.com/assets/13242287/22567806/000bb0c0-e957-11e6-91cd-e8d7e78817a7.png">

**Comment by djw8605** [comment]
Interesting.  It looks like it creates those files in the home directory when no full path is given.  Probably, it's just the directory that the job was submitted, which is the home directory.

Maybe we need another setting for setting the CWD?

**Comment by cjkeilig** [comment]
I was able to replicate the behavior above but only when the job file was in the $WORK directory. When I submit the job normally through HCCGo, the job file would appear in the $HOME but with no out or err files. HCCGo_tests is a $WORK directory correct? So, does slurm not have write access to $HOME? 
I'm still trying to find what exactly the 'fail' condition is.

**Comment by djw8605** [comment]
Yes, this is a symptom of the cluster configuration.  The output and error files are written from the worker nodes.  But, from the worker nodes, $HOME is not writable.  So the job fails, but no output or error because Slurm couldn't write them.

**Comment by cjkeilig** [comment]
Users are alerted if no full path is given for job location, job error or job output. The directory changes to their work directory when the submit button is pressed.

**Comment by cjkeilig** [comment]
This has been fixed.
