### ISSUE TITLE
Create a default job to get people started

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#149]
If the job submission history is empty, add a default hello-world job.

**Comment by adamfitzgibbon** [comment]
This should already be happening. Do you mean if a user were to delete their job template, to re-add it?

**Comment by djw8605** [comment]
Oh, I didn't see a default job when I installed HCCGo brand new.

**Comment by adamfitzgibbon** [comment]
I wonder if that's a lingering problem with initializing the db on startup. When I delete my jobHistory db it gets recreated on launch, but I'm not starting up a brand new installation.

**Comment by djw8605** [comment]
Ah, so when you delete your job history, there is still 1 job on startup?

**Comment by adamfitzgibbon** [comment]
If you delete it in the app it won't repopulate, but it will if you delete the file. It checks if a file is in the data directory and if not it creates a new one from the app/data/jobHistory.json file.

**Comment by adamfitzgibbon** [comment]
So not sure why it's not being created correctly on installation, but I remember you were having issues with that before, right? I thought we fixed that somehow though...

**Comment by djw8605** [comment]
Ok, that sounds good to me.
