### ISSUE TITLE
Diskusage DLL fails on Win10

### ISSUE THREAD

**Issue by robogen** [unlhcc/HCCGo#153]
Bug testing has shown that builds developed on a Win7 platform break once taken over to Win10, combination of differing permissions requirements and native library builds.

**Comment by djw8605** [comment]
I build the latest windows build on Win10.

**Comment by robogen** [comment]
Does your build work properly? Does that fix the issues?

**Comment by djw8605** [comment]
Nope, fails here too.  Same error as Natasha:

![image](https://cloud.githubusercontent.com/assets/79268/22612715/14afb5da-ea38-11e6-8d94-da2f16700c49.png)

**Comment by djw8605** [comment]
Fixed by merging in the #145

**Comment by djw8605** [comment]
The problem was that I had just installed the repo, and disk utility was updated. But, I hadn't updated the postinstall, so it wasn't building. I just pulled your solution, and everything worked. 

-Derek
