### ISSUE TITLE
File information on File Management screen

### ISSUE THREAD

**Issue by CarrieBrown** [unlhcc/HCCGo#158]
When clicking on a file, it would be helpful to display information about the file (such as size and maybe date created or modified) without having to click the download or upload file.

**Comment by cjkeilig** [comment]
![fileinfo](https://cloud.githubusercontent.com/assets/8206819/22904578/91ea0646-f202-11e6-92e5-9d2d73b70e0e.png)
Would something like this be good? The black info line pops up when the file is hovered over. This makes it so they don't have to click and look at the middle box.

**Comment by djw8605** [comment]
I'm wondering if that information could be displayed in the middle, under the download upload buttons.  Maybe, in a formatted display like a very simple table?  Include:

* Full path to file
* Size
* Last modified
