### ISSUE TITLE
Add "Clone" to job history

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#176]
Add a "Clone" or "Copy" button to copy an existing job to a new one, so you can still have both.

**Comment by adamfitzgibbon** [comment]
So given an entry in the job history page, just make a duplicate entry so they can resubmit the job with different commands but still have the old one saved?

**Comment by djw8605** [comment]
yes, exactly.

**Comment by djw8605** [comment]
by default, you can name it "Copy of X"

**Comment by adamfitzgibbon** [comment]
Addressed in #178
