### ISSUE TITLE
bower_components not properly getting copied to HCCGo/app/lib

### ISSUE THREAD

**Issue by robogen** [unlhcc/HCCGo#186]
I was working on my Windows machine and ended up doing a clean git clone repo. I noticed when doing a grunt run not all the files were getting downloaded to bower_components and not all files were getting copied properly to HCCGo/app/lib. If however I did a 'bower install' and then a grunt run, things worked just fine.

I did a fresh clone from unlhcc:master and confirmed the issue was there as well.

**Comment by djw8605** [comment]
"not all", which files were not downloaded?

**Comment by robogen** [comment]
the "js" folder in tether, the "js" files in selectivize. When copied the tether library wouldn't copy anything to the lib folder

**Comment by caseylargent** [comment]
Closed. Fixed with big UI change.
