### ISSUE TITLE
Clicking out of the File Management screen resets some of the display

### ISSUE THREAD

**Issue by CarrieBrown** [unlhcc/HCCGo#191]
File Management Screen Before:

![screen shot 2017-02-20 at 2 36 14 pm](https://cloud.githubusercontent.com/assets/13242287/23140962/0a960aa0-f77a-11e6-8549-42e76c97ab9b.png)

Clicking away from the File Management screen and going back to it causes it to change.

File Management Screen After:

![screen shot 2017-02-20 at 2 36 24 pm](https://cloud.githubusercontent.com/assets/13242287/23140983/1d1bd6f0-f77a-11e6-97c0-878566fdbde8.png)

The Remote panel switches to say "Home", while the directory is still work. And the "Switch to Home" button became "Switch to Work" even though work is the active directory.

**Comment by robogen** [comment]
Created a pull to fix this issue. Effectively, the explanation for this behavior is that we shouldn't use angular.element as much as possible.
