### ISSUE TITLE
Add option for shortcut on desktop for Windows installation

### ISSUE THREAD

**Issue by caseylargent** [unlhcc/HCCGo#194]

**Comment by djw8605** [comment]
We need to handle the arguments at the bottom of this:
https://github.com/electron/windows-installer

Should just be a bunch of copy / paste.

**Comment by djw8605** [comment]
I've started the work on my [windows_installer](https://github.com/djw8605/HCCGo/tree/windows_installer) branch.  I have it mostly working, just a few things need to be done:

- [ ] Fix Shortcut name, see https://github.com/electron/windows-installer/issues/115
- [ ] Add packaging scripts in the package.json for ease.

**Comment by djw8605** [comment]
Done in #200
