### ISSUE TITLE
Tutorial Repos

### ISSUE THREAD

**Issue by CarrieBrown** [unlhcc/HCCGo#201]
List of tutorial repos to be added. Additionally, the existing repo "HCCGoWorkshops" can be removed.

- [x] https://github.com/unlhcc/r-tutorial-beginner
- [x] https://github.com/unlhcc/r-tutorial-advanced

**Comment by djw8605** [comment]
The advanced repo doesn't have a `package.json`

**Comment by CarrieBrown** [comment]
Just pushed it now, should be fixed.

**Comment by djw8605** [comment]
Ok, done with those 2 repos: 081c7b6

Carrie, here is a zip of the archive: 
https://unl.box.com/s/z1uxex74jvffyr53xlva2dcjqmbwhv4k

**Comment by djw8605** [comment]
Fixes in v0.3.2
