### ISSUE TITLE
View on GitHub link not working

### ISSUE THREAD

**Issue by CarrieBrown** [unlhcc/HCCGo#208]
On the tutorials page, the `View on GitHub` link appears to be formatted like a hyperlink but does nothing when clicked.

**Comment by djw8605** [comment]
I see the bug, how urgent is this fix needed?

**Comment by CarrieBrown** [comment]
Not terribly. We won't be using that during the class.

**Comment by djw8605** [comment]
Ok, then I'll just fix the bug, but won't put out a new release.
