### ISSUE TITLE
Create a Text File Viewer

### ISSUE THREAD

**Issue by caseylargent** [unlhcc/HCCGo#221]
If the script is written in R, we need someway to show the output.

**Comment by djw8605** [comment]
For example, if the script is R, the output will be in a special Rout file.  We just need to be able to view that file, somehow.

**Comment by djw8605** [comment]
Should be integrated into the file transfer page.

**Comment by djw8605** [comment]
Just a few notes.

- Use https://www.npmjs.com/package/tmp to determine where to download the file.  And to clean up the file on exit.
- Also, use https://github.com/electron/electron/blob/master/docs/api/shell.md to open the file in the default manner.  May have to append a ".txt" to the end of the file so it opens in text editor.
