### ISSUE TITLE
Usability feedback from David

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#35]
Here is some usability feedback from David using it:

## File Transfer
- [x] The Switch button should be more clear.  Should be "Switch to Home", and "Switch to Work", and back and forth.
- [x] The icon for the switch should be different, makes it look like a refresh button.
- [x] To make it clear what directory you are in, maybe bold the `home` and `work` in the directory structure?

## Job Submission
- [x] Should check job directories so they can be written #34

**Comment by robogen** [comment]
Right on, David had mentioned the Switch button thing previously. I'll start working on these.

**Comment by djw8605** [comment]
Fixed in #42
