### ISSUE TITLE
Show completed jobs

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#41]
This will likely require some sort of saved state, a database with jobs?

**Comment by robogen** [comment]
I'm working on something related to this, there's a package I'm using to save setting data called electron-json-storage. It creates json files and stores them in the AppData directory of whatever operating system it runs on. If you want to see how I'm using that, my work with it is in my 'settings' branch. 

Or would you prefer a light weight database, like sqllite?

**Comment by djw8605** [comment]
I think we should use some sort of DB, like [nedb](https://github.com/louischatriot/nedb).

For settings, the electron-json-storage sounds great.

**Comment by robogen** [comment]
Glad you like it! But if that's the case, what about using [PouchDB](https://pouchdb.com/)? Seems to be the 'popular' option for apps like this right now

**Comment by djw8605** [comment]
Yeah, that’s a good alternative.  As long as it can save to a file, and not just indexdb.  It has to survive a HCCGo update (reinstall).

-Derek

**Comment by robogen** [comment]
Right right. I'll put some work into leveraging a (real) database then

**Comment by djw8605** [comment]
Eh. Nedb is probably real enough. Doesn't need to be fancy like sql lite. 

-Derek

**Comment by robogen** [comment]
Oh yea, that's what I mean. When I say a 'real' database I mean something that's not straight up flat file or json. I was gonna give PouchDB a try

**Comment by djw8605** [comment]
Finished in #45
