### ISSUE TITLE
Integrate Icons

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#43]
We now have icons.  @adamfitzgibbon can you put together a pull request with the new icons?  Make sure it all works in Mac.

[HCCGo Icons FINAL.zip](https://github.com/unlhcc/HCCGo/files/450615/HCCGo.Icons.FINAL.zip)

**Comment by djw8605** [comment]
I believe we use electron-packager.  So use this guide: https://github.com/electron-userland/electron-packager/blob/master/docs/api.md

**Comment by robogen** [comment]
The package.json file in the sub HCCGo folder will need to be edited, as that's where the package commands for the different platforms exist.

**Comment by adamfitzgibbon** [comment]
Addressed in #44

**Comment by djw8605** [comment]
Done in #44
