### ISSUE TITLE
Show Beta Summary Dialog

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#46]
When HCCGo starts up, it should show a "Beta" dialog, describing that to expect problems.  And also a note in the top to say that it's in "Beta", so we can manage expectations.

**Comment by robogen** [comment]
I can take a look into doing this, mind making me the assignee?

**Comment by robogen** [comment]
When you say dialog, would you like the notification to be its own window that pops up over the main window? Technically independent of the main application?

And when you say 'top', would you like that in the nav bar so it's easily visible inside the application, or would you like that in the title bar?

**Comment by djw8605** [comment]
Dialog: Just a HTML dialog modal.  Not an independent window, want it very in front of the user.

For the "Beta" tag, I want it in the nav bar.  Probably in the top left just next to the logo.

**Comment by djw8605** [comment]
Finished in #47
