### ISSUE TITLE
Move transfers to a service

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#58]
Move transfers to a service, so you can navigate away from the page, and the transfers can continue.  Also, you should be able to go back to the transfers page, and see the active transfers.

**Comment by robogen** [comment]
I've done a little bit of work towards this, but it'll be a bit before anything demonstrable. With finals approaching and projects finishing, I should have something in 2-3 weeks.

**Comment by djw8605** [comment]
Fixed in 299ade898c7691b4108079afa982741c5f4a9641
