### ISSUE TITLE
View stdout/stderr of job

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#66]
We already know where the stdout and stderr of the job are located.  We should provide a viewer for the contents of stdout / stderr.  Probably be a whole new page.

**Comment by adamfitzgibbon** [comment]
What did you have in mind for this? As in would it be a whole new main page that is navigated to from the the nav bar, or maybe something more minor? It would probably be really simple to just add in the stderr/stdout onto data that is stored on job completion, and then there could just be an info button on the completed jobs that would pull up the information. Of course that could get cumbersome because it would mean pulling up a modal each time a completed job is clicked.

**Comment by djw8605** [comment]
I think it will be a new page, but it will not be in the top bar.  It should be navigable from a completed job (imagine a new button that says "View Output & Error" in a completed job's well).

I wonder if we should store the output/error, in the DB at all?  Maybe just pull it from the cluster each time?

**Comment by adamfitzgibbon** [comment]
What's the reason to pull it every time? If they re-run a job, shouldn't that come up as a new "completed job" in HCCGo?

**Comment by djw8605** [comment]
I'm worried about how big the stdout or stderr could be.  As long as there are some reasonable barriers, like not download the stdout / stderr if they are larger than 5MB?

**Comment by adamfitzgibbon** [comment]
Oh I see, you're thinking huge strings of output could clog up the local DB? So do you mean store them if they are small enough or still pull every time but only pull small enough output?

**Comment by djw8605** [comment]
I think there are these states.  Each the output and error should be considered separately.

* If the output and/or stderr is smaller 5MB, download and store it in the DB.  And show it when requested.
* If the output and/or stderr is larger than 5MB, do not download the output.  Instead, list an error when they try to view it (and give the size of the output), and give a link to the file transfer page so they can transfer the output.

**Comment by djw8605** [comment]
Adam, I put this as the highest priority item for HCCGo currently.  Do you need any help?  I have some other undergrads now.

**Comment by adamfitzgibbon** [comment]
Sorry for the delay, I didn't work over break except for a couple hours here and there when I pushed those quick fixes a few weeks ago. My class schedule this semester will only permit me to come in Wednesday morning and most of Friday, so I'll make sure to get caught up with all the changes you've made and let you know where I'm at for this issue tomorrow morning.

**Comment by djw8605** [comment]
Done in #115
