### ISSUE TITLE
JobName with spaces breaks submission

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#67]
JobName with spaces breaks submission

**Comment by adamfitzgibbon** [comment]
Oh that's a bummer, didn't think to sanitize for the command. Are there any other special characters that might break the command?

**Comment by djw8605** [comment]
![image](https://cloud.githubusercontent.com/assets/79268/20774478/1b14ce5a-b71c-11e6-8ddb-f4d27f49f922.png)

**Comment by djw8605** [comment]
Fixed in #74
