### ISSUE TITLE
Job Submission modules list

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#68]
From tester:
> When you're in the module field is there a way to have the drop down only show up if you start typing or click? Otherwise, if you get tab happy, you can add modules you don't mean to.

**Comment by adamfitzgibbon** [comment]
I think not opening up the dropdown on focus is a little tough to do, but removing the ability to select on tab is as easy as changing an option in the selectize initialization. Is that an acceptable solution to this request?
