### ISSUE TITLE
Store cluster and other information in rootScope or Service

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#77]
Currently, the routed URL holds the cluster we are currently logged into.  We should instead use some service or variable to store the currently logged in Cluster.

**Comment by adamfitzgibbon** [comment]
Was this already addressed somewhere? This information seems to already be stored in the connection service and fetched from that by the nav service.

**Comment by djw8605** [comment]
Yes. This can be closed. It's in connection service now. 

-Derek
